### ISSUE TITLE
problem with argparse in computeGCbias

### ISSUE THREAD

**Issue by vivekbhr** [fidelram/deepTools#209]
computeGCbias is broken currently due to some minor(I think) argparse problem. I can't find which argument is causing this but when I do `computeGCBias -h` , I get : 

```

Traceback (most recent call last):
  File "/package/deeptools-2.0.0/bin/computeGCBias", line 7, in <module>
    main()
  File "/package/deeptools-2.0.0/lib/python2.7/site-packages/deeptools/computeGCBias.py", line 638, in main
    args = parse_arguments().parse_args(args)
  File "/usr/lib64/python2.7/argparse.py", line 1688, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1720, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1926, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python2.7/argparse.py", line 1866, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python2.7/argparse.py", line 1794, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python2.7/argparse.py", line 994, in __call__
    parser.print_help()
  File "/usr/lib64/python2.7/argparse.py", line 2327, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib64/python2.7/argparse.py", line 2301, in format_help
    return formatter.format_help()
  File "/usr/lib64/python2.7/argparse.py", line 279, in format_help
    help = self._root_section.format_help()
  File "/usr/lib64/python2.7/argparse.py", line 209, in format_help
    func(*args)
  File "/usr/lib64/python2.7/argparse.py", line 209, in format_help
    func(*args)
  File "/usr/lib64/python2.7/argparse.py", line 515, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib64/python2.7/argparse.py", line 601, in _expand_help
    return self._get_help_string(action) % params
TypeError: float argument required, not dict


```

**Comment by dpryan79** [comment]
This was my fault. When I modified some of the English I put in "%GC", which breaks argparse.

**Comment by dpryan79** [comment]
This will get fixed whenever my remote-file-test branch gets finished and merged in.

**Comment by vivekbhr** [comment]
@dpryan79 great :+1:
