### ISSUE TITLE
pyBigWig.so problem

### ISSUE THREAD

**Issue by AlicePsyche** [fidelram/deepTools#214]
Hi, 
Recently I install deeptools on my own Mac but I found that everything related with bigfile has a problem. When I ran bigwigCompare or computeMatrix or any command invoke pyBigWig.so, the error message 

```bash
Traceback (most recent call last):
  File "/Users/Alice/anaconda2/bin/computeMatrix", line 4, in <module>
    from deeptools.computeMatrix import main
  File "/Users/Alice/anaconda2/lib/python2.7/site-packages/deeptools/computeMatrix.py", line 14, in <module>
    from deeptools import heatmapper
  File "/Users/Alice/anaconda2/lib/python2.7/site-packages/deeptools/heatmapper.py", line 11, in <module>
    import pyBigWig
ImportError: dlopen(/Users/Alice/anaconda2/lib/python2.7/site-packages/pyBigWig.so, 2): Library not loaded: libcurl.4.dylib
  Referenced from: /Users/Alice/anaconda2/lib/python2.7/site-packages/pyBigWig.so
  Reason: Incompatible library version: pyBigWig.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
```

But when I found libcurl 

```bash
locate libcurl.4.dylib | xargs otool -L
```
I found that 
```bash
/Users/Alice/anaconda2/lib/libcurl.4.dylib:
	libcurl.4.dylib (compatibility version 9.0.0, current version 9.0.0)
	@loader_path/./libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@loader_path/./libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@loader_path/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
/Users/Alice/anaconda2/pkgs/curl-7.45.0-0/lib/libcurl.4.dylib:
	libcurl.4.dylib (compatibility version 9.0.0, current version 9.0.0)
	@loader_path/./libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@loader_path/./libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@loader_path/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
/usr/lib/libcurl.4.dylib:
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 57330.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1230.0.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.0.0)
```

and my PATH

```bash
/usr/local/opt/git/bin:/Users/Alice/anaconda2/lib:/Users/Alice/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

My curl

```bash
curl --version
curl 7.46.0 (x86_64-apple-darwin15.0.0) libcurl/7.46.0 SecureTransport zlib/1.2.5
```

My mac run EI capitan. I am not familar with python. what libcurl.4.dylib did pyBigWig use? Does it use the one in anaconda?

**Comment by dpryan79** [comment]
Anaconda is unfortunately broken. While I have a fix for this working under
Linux (conda install -c bioconda pybigwig), it's not yet working under OSX.
So you'll have to not use anaconda there (just "pip install ...").

Devon

--
Devon Ryan, Ph.D.
Email: dpryan@dpryan.com
Data Manager/Bioinformatician
Max Planck Institute of Immunobiology and Epigenetics
Stübeweg 51
79108 Freiburg
Germany
<devon.ryan@dzne.de>

**Comment by AlicePsyche** [comment]
Now i use pip but the problem is still there.

```bash
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/pyBigWig.so, 2): Library not loaded: libcurl.4.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/pyBigWig.so
  Reason: Incompatible library version: pyBigWig.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
```

I don't think the problem is conda, it should be pyBigWig or libcurl.

I have update pyBigWig

```bash
pip install pyBigWig --upgrade
Requirement already up-to-date: pyBigWig in /usr/local/lib/python2.7/site-packages
```

**Comment by dpryan79** [comment]
Weird, I'll have a look, though I suspect I'll have a fix in place for anaconda by the end of the day.

**Comment by dpryan79** [comment]
This is now available in conda in OSX via `conda install -c bioconda pybigwig`. I'll see if I can get a system with OSX and homebrew to test the normal pip stuff tomorrow.

**Comment by dpryan79** [comment]
This seems to work now with the system python too (at least if you have `pip` installed):
```
$ sw_vers -productVersion
10.9.5
$ python --version
Python 2.7.5
$ which python
/usr/bin/python
$  pip install pyBigWig --user
Collecting pyBigWig
  Using cached pyBigWig-0.2.3.tar.gz
Installing collected packages: pyBigWig
  Running setup.py install for pyBigWig
Successfully installed pyBigWig-0.2.3
$ nosetests pyBigWigTest -s -v
pyBigWigTest.test.TestLocal.testFoo ... /home/ryan/Library/Python/2.7/lib/python/site-packages/pyBigWigTest/test.bw
ok
pyBigWigTest.test.TestRemote.testAll ... https://raw.githubusercontent.com/dpryan79/pyBigWig/master/pyBigWigTest/test.bw
ok

----------------------------------------------------------------------
Ran 2 tests in 0.795s

OK
```
