### ISSUE TITLE
plotEnrichment parameters --extendReads and --blackListFileName cause crash

### ISSUE THREAD

**Issue by asrichter** [fidelram/deepTools#384]
The plotEnrichment parameter `--extendReads` gives the following runtime error:

```
$ /package/deeptools-develop-python2/bin/plotEnrichment -b Input_F.filtered.bam H3K27ac_F.filtered.bam \
--BED gencode.release_19.genes.gtf --plotFile plot.png -p 24 --extendReads 
Traceback (most recent call last):
  File "/package/deeptools-develop-python2/bin/plotEnrichment", line 7, in <module>
    main()
  File "/package/deeptools-develop-python2/lib/python2.7/site-packages/deeptools/plotEnrichment.py", line 434, in main
    verbose=args.verbose)
  File "/package/deeptools-develop-python2/lib/python2.7/site-packages/deeptools/mapReduce.py", line 141, in mapReduce
    res = pool.map_async(func, TASKS).get(9999999)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
RuntimeError: pyFindOverlaps received an invalid or missing argument!
```

Without `--extendReads`, the tool finishes normally.

Also, the plotEnrichment parameter `--blackListFileName` gives the following type error:
```
$ /package/deeptools-develop-python2/bin/plotEnrichment -b Input_F.filtered.bam H3K27ac_F.filtered.bam \
--BED gencode.release_19.genes.gtf --plotFile plot.png --blackListFileName hs37d5_extended_Encode-blacklist.bed -p 24
Traceback (most recent call last):
  File "/package/deeptools-develop-python2/bin/plotEnrichment", line 7, in <module>
    main()
  File "/package/deeptools-develop-python2/lib/python2.7/site-packages/deeptools/plotEnrichment.py", line 424, in main
    chunkLength = getChunkLength(args, chromSize)
  File "/package/deeptools-develop-python2/lib/python2.7/site-packages/deeptools/plotEnrichment.py", line 353, in getChunkLength
    regs = blSubtract(bl, k, (0, v))
  File "/package/deeptools-develop-python2/lib/python2.7/site-packages/deeptools/mapReduce.py", line 254, in blSubtract
    chunk[0] = o[1]
TypeError: 'tuple' object does not support item assignment
```

**Comment by dpryan79** [comment]
I just pushed the fix for the `--extendReads` issue. I'll look into the black list problem now too.

**Comment by dpryan79** [comment]
I had a couple minutes before the game started, so the blacklist issue is now fixed.
