### ISSUE TITLE
multiBamSummary bins with --outRawCounts dies in an error.

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#407]
multiBamSummary bins -p 1 --region chr1 -b ENCFF001FWO.bam ENCFF030VNO.bam -o results.npz --outRawCounts readcounts.tab

Causes this:

    Traceback (most recent call last):
      File "/home/ryan/.local/bin/multiBamSummary", line 11, in <module>
        main(args)
      File "/home/ryan/.local/lib/python2.7/site-packages/deeptools/multiBamSummary.py", line 225, in main
        num_reads_per_bin = c.run(allArgs=args)
      File "/home/ryan/.local/lib/python2.7/site-packages/deeptools/countReadsPerBin.py", line 296, in run
        transcript_id_designator=transcript_id_designator)
      File "/home/ryan/.local/lib/python2.7/site-packages/deeptools/mapReduce.py", line 144, in mapReduce
        res = list(map(func, TASKS))
      File "/home/ryan/.local/lib/python2.7/site-packages/deeptools/countReadsPerBin.py", line 27, in countReadsInRegions_wrapper
        return CountReadsPerBin.count_reads_in_region(*args)
      File "/home/ryan/.local/lib/python2.7/site-packages/deeptools/countReadsPerBin.py", line 438, in count_reads_in_region
        _file.write("\t".join(["{}".format(x) for x in subnum_reads_per_bin[idx, :]]) + "\n")
    IndexError: index 24 is out of bounds for axis 0 with size 24

I'm not sure if this is only when `bins` is uses or if regions are specified too. This was first reported by Astrid Böhne on the mailing list.

**Comment by dpryan79** [comment]
I found the cause of this. Bins smaller than the desired bin size (e.g., due to being at the end of a chromosome) aren't created, but the `range()` iterator used for writing the output doesn't honour this, due to the start region of the bin (but not the end!) being within the range given the step size. The fix is quite simple and now implemented.

**Comment by dpryan79** [comment]
I'll close this once 2.3.4 is released.
