### ISSUE TITLE
plotHeatmap --sortUsing region_length error

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#435]
This is courtesy of Carlos Guzman on the mailing list:

    plotHeatmap -m CM_MNase_Regions_Ctrl -out HM_MNase_Regions_Ctrl.png --dpi 300 --colorMap RdBu --refPointLabel center --sortUsing region_length

produces:

    Traceback (most recent call last):
      File "/usr/local/anaconda2/bin/plotHeatmap", line 7, in <module>
        main()
      File "/usr/local/anaconda2/lib/python2.7/site-packages/deeptools/plotHeatmap.py", line 584, in main
        sample_list=sortUsingSamples)
      File "/usr/local/anaconda2/lib/python2.7/site-packages/deeptools/heatmapper.py", line 1124, in sort_groups
        for x in self.regions])
    TypeError: list indices must be integers, not str

It looks like we just need to `x[2] - x[1]` or something along those lines.

**Comment by dpryan79** [comment]
@vivekbhr: This should be fixed in `develop`. Since you mentioned running into this recently, can you double check that it's producing reasonable results now?

**Comment by vivekbhr** [comment]
ok I am testing..

**Comment by vivekbhr** [comment]
On my data, plotHeatmap (latest pull from develop) throws the following error.

```
('Samples used for ordering within each group: ', [])
Traceback (most recent call last):
  File "/home/bhardwaj/programs/anaconda/bin/plotHeatmap", line 7, in <module>
    main()
  File "/home/bhardwaj/programs/anaconda/lib/python2.7/site-packages/deeptools/plotHeatmap.py", line 585, in main
    sample_list=sortUsingSamples)
  File "/home/bhardwaj/programs/anaconda/lib/python2.7/site-packages/deeptools/heatmapper.py", line 1100, in sort_groups
    for x in self.regions])
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

other options working fine

**Comment by dpryan79** [comment]
@vivekbhr: You're not using the develop branch.

**Comment by vivekbhr** [comment]
@dpryan79 That's right.! The git pull didn't work last time.. my bad..

It works nicely now..!

**Comment by dpryan79** [comment]
Cool, thanks! I can close this with confidence then :)
