### ISSUE TITLE
Odd --sortRegions keep issue

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#451]
This was reported today internally. Sometimes computeMatrix will crash with:

    Traceback (most recent call last):
     File "/package/deeptools-2.4.0/bin/computeMatrix", line 11, in <module>
       main(args)
     File "/package/deeptools-2.4.0/lib/python3.4/site-packages/deeptools/computeMatrix.py", line 430, in main
       cmo.sortMatrix(hm, args.regionsFileName, args.transcriptID, args.transcript_id_designator)
     File "/package/deeptools-2.4.0/lib/python3.4/site-packages/deeptools/computeMatrixOperations.py", line 621, in sortMatrix
       for k, v in regions[idx].items():

I have the full command so I'll have a look.

**Comment by dpryan79** [comment]
The problem only occurs with BED files that have a `deepTools_group` column. In this case, the regions are all stored in a list, rather than a dict, which is a bug.

**Comment by dpryan79** [comment]
This should now be fixed in the `develop` branch.
