### ISSUE TITLE
1-base BED entries with center

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#456]
I thought I had fixed this already, but 1-base entries can cause problems with `--referencePoint center`:

    Traceback (most recent call last):
      File "/package/deeptools-2.4.1/bin/computeMatrix", line 11, in <module>
        main(args)
      File "/package/deeptools-2.4.1/lib/python2.7/site-packages/deeptools/computeMatrix.py", line 414, in main
        hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
      File "/package/deeptools-2.4.1/lib/python2.7/site-packages/deeptools/heatmapper.py", line 247, in computeMatrix
        keepExons=keepExons)
      File "/package/deeptools-2.4.1/lib/python2.7/site-packages/deeptools/mapReduce.py", line 144, in mapReduce
        res = list(map(func, TASKS))
      File "/package/deeptools-2.4.1/lib/python2.7/site-packages/deeptools/heatmapper.py", line 173, in compute_sub_matrix_wrapper
        return heatmapper.compute_sub_matrix_worker(*args)
      File "/package/deeptools-2.4.1/lib/python2.7/site-packages/deeptools/heatmapper.py", line 454, in compute_sub_matrix_worker
        upstream.insert(0, (upstream[0][0] - padLeft, upstream[0][0]))

**Comment by dpryan79** [comment]
This is now fixed in `develop`.
