### ISSUE TITLE
error with deep_bam_coverage (and deeptools_plot_correlation) (Galaxy Version 2.4.2.0)

### ISSUE THREAD

**Issue by drosofff** [fidelram/deepTools#476]
Hi @bgruening 

I have a Mississippi.fr user who reports problems with deeptools.
I did a planemo test of deep_bam_coverage [here](https://gist.github.com/drosofff/208b927db711cfad69bbe3d9dcd1aa27) and had indeed a problem (galaxy instance 16_07 for planemo)

I had also errors (but empty test output) with the deeptools_plot_correlation.

Any suggestion ? I am not super familiar with this tool suite.

Best. Chris

**Comment by bgruening** [comment]
@drosofff which problem did your users encountered? The link error only indicates that you have no deeptools accessible for planemo, e.g. you did not the `planemo conda_install` before.
The test should indeed pass, as we are testing them here on travis with every change. But the test coverage is not 100% so maybe we missed something.

Also can you tell us with deeptools version are you using?

**Comment by drosofff** [comment]
on mississippi, suite_deeptools 6012d99a9d30, version 2.4.2.0. I upgraded yesterday.

First error report on deeptools_plot_correlation (previous version)
```
Detailed Job Information

Job environment and execution information is available at the job Info Page.
Job ID	126868 (724f96ac36f6da91)
Tool ID	toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_plot_correlation/deeptools_plot_correlation/2.2.3.0
Tool Version	2.2.3.0
Job PID or DRM id	29151
Job Tool Version	Traceback (most recent call last): File "/home/galaxy/tool_dependency/deepTools/2.2.3/iuc/package_python_2_7_deeptools_2_2_3/2f4601e4fc32/bin/plotCorrelation", line 4, in <module> from deeptools.plotCorrelation import main File "/home/galaxy/tool_dependency/deepTools/2.2.3/iuc/package_python_2_7_deeptools_2_2_3/2f4601e4fc32/lib/python/deeptools/plotCorrelation.py", line 11, in <module> from deeptools.correlation import Correlation File "/home/galaxy/tool_dependency/deepTools/2.2.3/iuc/package_python_2_7_deeptools_2_2_3/2f4601e4fc32/lib/python/deeptools/correlation.py", line 5, in <module> import scipy.stats File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/stats/__init__.py", line 334, in <module> from .stats import * File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/stats/stats.py", line 186, in <module> from . import distributions File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/stats/distributions.py", line 10, in <module> from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous, File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/stats/_distn_infrastructure.py", line 25, in <module> from scipy import integrate File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/integrate/__init__.py", line 52, in <module> from .odepack import * File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/integrate/odepack.py", line 6, in <module> from . import _odepack ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
Job Execution and Failure Information

Command Line

plotCorrelation --corData "/home/galaxy/galaxy-dist/database/files/000/172/dataset_172863.dat" --plotFile "/home/galaxy/galaxy-dist/database/files/000/172/dataset_172867.dat" --corMethod "spearman" --whatToPlot "scatterplot" --plotTitle 'General correlation Chromatin RNAs'  --plotFileFormat "pdf" --removeOutliers --outFileCorMatrix "/home/galaxy/galaxy-dist/database/files/000/172/dataset_172868.dat"
stderr

Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/home/galaxy/tool_dependency/deepTools/2.2.3/iuc/package_python_2_7_deeptools_2_2_3/2f4601e4fc32/bin/plotCorrelation", line 4, in <module>
    from deeptools.plotCorrelation import main
  File "/home/galaxy/tool_dependency/deepTools/2.2.3/iuc/package_python_2_7_deeptools_2_2_3/2f4601e4fc32/lib/python/deeptools/plotCorrelation.py", line 11, in <module>
    from deeptools.correlation import Correlation
  File "/home/galaxy/tool_dependency/deepTools/2.2.3/iuc/package_python_2_7_deeptools_2_2_3/2f4601e4fc32/lib/python/deeptools/correlation.py", line 5, in <module>
    import scipy.stats
  File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/stats/__init__.py", line 334, in <module>
    from .stats import *
  File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/stats/stats.py", line 186, in <module>
    from . import distributions
  File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/stats/distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
  File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/stats/_distn_infrastructure.py", line 25, in <module>
    from scipy import integrate
  File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/integrate/__init__.py", line 52, in <module>
    from .odepack import *
  File "/home/galaxy/tool_dependency/scipy/0.14/iuc/package_python_2_7_scipy_0_14/7fddd308117d/lib/python/scipy/integrate/odepack.py", line 6, in <module>
    from . import _odepack
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

stdout


Job Information

None
Job Traceback

None
```

Second error on deep_bam_coverage ugraded version
```
Dear Christophe, 

thanks for your quick reply. I have been trying to rerun the analysis using the new version 2.4.2 but with no success. When trying to generate a multiBAMSummary for my BAM files it gives the following error:

Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/home/galaxy/tool_dependency/deeptools/2.4.2/iuc/package_python_2_7_deeptools_2_4_2/efc55c226f11/bin/multiBamSummary", line 4, in <module>
    from deeptools.multiBamSummary import main
  File "/home/galaxy/tool_dependency/deeptools/2.4.2/iuc/package_python_2_7_deeptools_2_4_2/efc55c226f11/lib/python/deeptools/multiBamSummary.py", line 9, in <module>
    import deeptools.countReadsPerBin as countR
  File "/home/galaxy/tool_dependency/deeptools/2.4.2/iuc/package_python_2_7_deeptools_2_4_2/efc55c226f11/lib/python/deeptools/countReadsPerBin.py", line 13, in <module>
    import pyBigWig
ImportError: No module named pyBigWig
```
My bad for planemo, I forgot conda_install indeed.
I will retest later

**Comment by bgruening** [comment]
This really looks like an installation problem in general. Are you using a conda enabled Galaxy already or the classic tool_dependencies.xml files?

**Comment by drosofff** [comment]
Yes I think so. But Galaxy mississippi is conda enabled since ~6 months, so far without major problems. The conda panel in the tool admin interface looks ok too for the deeptools.

**Comment by bgruening** [comment]
The error indicates that It it not using conda :(

**Comment by drosofff** [comment]
This is true  indeed ! Thanks for bringing my attention to this ;-) (toolshed resolver instead of conda).

Yet this gave me the occasion to verify other tools that are installed with the conda resolver.

Did I missed an option at latest deeptools install ? I'll check and keep you posted

**Comment by drosofff** [comment]
Ok I fixed the deep_bam_coverage issue by repairing dependency installation. The deeptools_plot_correlation still fails. However as I get the same error in http://deeptools.ie-freiburg.mpg.de/ I suspect the input data to be wrong...
Thanks

**Comment by dpryan79** [comment]
The file you're uploading for use with `plotCorrelation` is essentially empty (it's a numpy matrix with no values), which is why you're getting this error.

**Comment by drosofff** [comment]
Hurrah ! uninstalling previous dependencies versions and/or a bit of repo repair fixed it.  I am still confused about the suite that does not seem to be able to work with exclusively conda dependencies (even in a couple of clean galaxy instances that I spin off for tests). But I may be wrong and I am lacking time to track properly the problem. As a matter of fact, it works. Feel free to close the issue and sorry for the noise.
Best

**Comment by dpryan79** [comment]
Glad it's all working for you now!
