### ISSUE TITLE
bamCoverage: TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by chrarnold** [fidelram/deepTools#491]
Since a recent update of all packages and deepTools, I receive the following error when running bamCoverage using BOTH the --extendReads and --centerReads parameter, either one of these 2 parameters works fine, but not the combination. The exact same command worked before (see below), the BAM file is also fine.

bamCoverage   --bam test2.merged.final.bam  --binSize 10  --centerReads --extendReads   --outFileName test2.merged.final.bigwig  --outFileFormat bigwig --region chr21
region: chr21:10
verbose: False
center_read: True
bamFilesList: ['test2.merged.final.bam']
ignoreDuplicates: False
samFlag_include: None
numberOfProcessors: 4
bedFile: None
out_file_for_raw_data: None
save_data: False
numberOfSamples: None
blackListFileName: None
chrsToSkip: []
stepSize: 10
defaultFragmentLength: 56
smoothLength: None
zerosToNans: False
maxPairedFragmentLength: 224
minFragmentLength: 0
minMappingQuality: None
maxFragmentLength: 0
binLength: 10
samFlag_exclude: None
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File ".../miniconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File ".../miniconda3/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File ".../miniconda3/lib/python3.5/site-packages/deeptools/writeBedGraph.py", line 28, in writeBedGraph_wrapper
    return WriteBedGraph.writeBedGraph_worker(*args)
  File ".../miniconda3/lib/python3.5/site-packages/deeptools/writeBedGraph.py", line 227, in writeBedGraph_worker
    coverage, _ = self.count_reads_in_region(chrom, start, end)
  File ".../miniconda3/lib/python3.5/site-packages/deeptools/countReadsPerBin.py", line 446, in count_reads_in_region
    tcov = self.get_coverage_of_region(bam, chrom, trans)
  File ".../miniconda3/lib/python3.5/site-packages/deeptools/countReadsPerBin.py", line 628, in get_coverage_of_region
    coverages[sIdx:eIdx] += 1
TypeError: slice indices must be integers or None or have an __index__ method
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../miniconda3/bin/bamCoverage", line 11, in <module>
    main(args)
  File ".../miniconda3/lib/python3.5/site-packages/deeptools/bamCoverage.py", line 255, in main
    format=args.outFileFormat, smoothLength=args.smoothLength)
  File ".../miniconda3/lib/python3.5/site-packages/deeptools/writeBedGraph.py", line 141, in run
    numberOfProcessors=self.numberOfProcessors)
  File ".../miniconda3/lib/python3.5/site-packages/deeptools/mapReduce.py", line 142, in mapReduce
    res = pool.map_async(func, TASKS).get(9999999)
  File ".../miniconda3/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
TypeError: slice indices must be integers or None or have an __index__ method
```
I believe this error is related to the following warning that I received earlier, that however did not result in an error and produced the correct output file:

`.../miniconda3/lib/python3.5/site-packages/deeptools/countReadsPerBin.py:628: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future`

Any suggestions how to fix it? Sounds like an implementation issue. All my conda packages are up to date, and I even installed deepTools only in an isolated conda environment to make sure there is no possible interference with other tools. I am using deepTools 2.4.2

**Comment by dpryan79** [comment]
That's very strange. Can you post your BAM file somewhere (you can create an account on deeptools.ie-freiburg.mpg.de and ftp the file there if needed)?

**Comment by chrarnold** [comment]
Hi, strange indeed. This is from ATAC-Seq data. I can provide a Dropbox link, but I'd rather do this non-publicly, can I send you an email or something with the link? Thanks for the quick help!

**Comment by dpryan79** [comment]
Certainly, you can use my institute email address: ryan@ie-freiburg.mpg.de

**Comment by dpryan79** [comment]
This is now available in pypi and will be available in conda whenever TravisCI is finished.

**Comment by SheilaTeves** [comment]
Hello, I recently got this same error when doing --MNase option combined with --minFragmentLength and --maxFragmentLength.

bamFilesList: ['ATAC2_rep1_sorted.bam']
binLength: 10
numberOfSamples: None
blackListFileName: None
defaultFragmentLength: read length
numberOfProcessors: 6
verbose: False
region: None
bedFile: None
minMappingQuality: None
ignoreDuplicates: True
chrsToSkip: []
stepSize: 10
center_read: False
samFlag_include: None
samFlag_exclude: None
minFragmentLength: 150
maxFragmentLength: 250
zerosToNans: False
smoothLength: None
save_data: False
out_file_for_raw_data: None
maxPairedFragmentLength: 250
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/lab2/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/lab2/anaconda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/lab2/anaconda/lib/python3.6/site-packages/deeptools/writeBedGraph.py", line 28, in writeBedGraph_wrapper
    return WriteBedGraph.writeBedGraph_worker(*args)
  File "/Users/lab2/anaconda/lib/python3.6/site-packages/deeptools/writeBedGraph.py", line 227, in writeBedGraph_worker
    coverage, _ = self.count_reads_in_region(chrom, start, end)
  File "/Users/lab2/anaconda/lib/python3.6/site-packages/deeptools/countReadsPerBin.py", line 446, in count_reads_in_region
    tcov = self.get_coverage_of_region(bam, chrom, trans)
  File "/Users/lab2/anaconda/lib/python3.6/site-packages/deeptools/countReadsPerBin.py", line 629, in get_coverage_of_region
    coverages[sIdx:eIdx] += 1
TypeError: slice indices must be integers or None or have an __index__ method
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lab2/anaconda/bin/bamCoverage", line 11, in <module>
    main(args)
  File "/Users/lab2/anaconda/lib/python3.6/site-packages/deeptools/bamCoverage.py", line 238, in main
    format=args.outFileFormat, smoothLength=args.smoothLength)
  File "/Users/lab2/anaconda/lib/python3.6/site-packages/deeptools/writeBedGraph.py", line 141, in run
    numberOfProcessors=self.numberOfProcessors)
  File "/Users/lab2/anaconda/lib/python3.6/site-packages/deeptools/mapReduce.py", line 142, in mapReduce
    res = pool.map_async(func, TASKS).get(9999999)
  File "/Users/lab2/anaconda/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
TypeError: slice indices must be integers or None or have an __index__ method

Any thoughts?

Thanks!

Sheila

**Comment by dpryan79** [comment]
@SheilaTeves What version are you using?

**Comment by SheilaTeves** [comment]
Oh, I still have 2.5.1. I will upgrade and check if it's still an issue
