### ISSUE TITLE
error with bamCoverage --extendReads (depptools 2.3 -> 2.5.0.1)

### ISSUE THREAD

**Issue by lelouar** [fidelram/deepTools#513]
Hi,

I just updated deeptools and I had error with --extendReads option. Without this option it seems to work fine. The previous version I had is 2.2.4, I reinstall it and no error, I tried to install next version (2.3) and the same error occurs.

here the log:
"""
Traceback (most recent call last):
  File "/mnt/data1/raoul.raffel/commun/tools/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/data1/raoul.raffel/commun/tools/lib/python3.4/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/data1/raoul.raffel/commun/tools/testDeeptools/lib/python3.4/site-packages/deeptools/getFragmentAndReadSize.py", line 11, in getFragmentLength_wrapper
    return getFragmentLength_worker(*args)
  File "/mnt/data1/raoul.raffel/commun/tools/testDeeptools/lib/python3.4/site-packages/deeptools/getFragmentAndReadSize.py", line 49, in getFragmentLength_worker
    for r in bam.fetch(chrom, start, end)])
  File "/mnt/data1/raoul.raffel/commun/tools/testDeeptools/lib/python3.4/site-packages/deeptools/getFragmentAndReadSize.py", line 49, in <listcomp>
    for r in bam.fetch(chrom, start, end)])
TypeError: infer_query_length() takes no keyword arguments
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/data1/raoul.raffel/commun/tools/testDeeptools/bin/bamCoverage", line 11, in <module>
    main(args)
  File "/mnt/data1/raoul.raffel/commun/tools/testDeeptools/lib/python3.4/site-packages/deeptools/bamCoverage.py", line 249, in main
    verbose=args.verbose,
  File "/mnt/data1/raoul.raffel/commun/tools/testDeeptools/lib/python3.4/site-packages/deeptools/countReadsPerBin.py", line 176, in __init__
    verbose=verbose)
  File "/mnt/data1/raoul.raffel/commun/tools/testDeeptools/lib/python3.4/site-packages/deeptools/getFragmentAndReadSize.py", line 96, in get_read_and_fragment_length
    verbose=verbose)
  File "/mnt/data1/raoul.raffel/commun/tools/testDeeptools/lib/python3.4/site-packages/deeptools/mapReduce.py", line 142, in mapReduce
    res = pool.map_async(func, TASKS).get(9999999)
  File "/mnt/data1/raoul.raffel/commun/tools/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
TypeError: infer_query_length() takes no keyword arguments

I will return to previous version now.
many thanks

**Comment by dpryan79** [comment]
Downgrade pysam to 0.10.0. The most recent release changed the API and broke a LOT of code :(

**Comment by lelouar** [comment]
its works

many thanks

**Comment by dpryan79** [comment]
I wish it had never broken :(
Xref: https://github.com/pysam-developers/pysam/issues/440
