### ISSUE TITLE
TypeError: infer_query_length() takes no keyword arguments

### ISSUE THREAD

**Issue by LucoLab** [fidelram/deepTools#515]
Using Python 3.5.2 :: Anaconda custom (64-bit) & deeptools 2.5.0.1

I'm using the following command : 

`bamCoverage -b K4ME1/mapping/hg38/Luco_2_3.sorted.bam -o K4ME1/bigwig/hg38/Luco_2_3TEST.bw --normalizeUsingRPKM --numberOfProcessors 10 --binSize 10   --extendReads 200 --smoothLength 30 --ignoreDuplicates --minMappingQuality 20 --verbose &>K4ME1/bigwig/hg38/Luco_2_3TEST.bw.log`

Get the following error : 
`genome partition size for multiprocessing: 1000000
using 10 processors for 3273 number of tasks
Due to filtering, 54.800074345489044% of the aforementioned alignments will be used 90313060.86080964
Final scaling factor: 1.1072595596568235
genome partition size for multiprocessing: 1050000
using 10 processors for 3123 number of tasks
normalization: RPKM
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/test/bin/python-3.5-2/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/test/bin/python-3.5-2/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/test/bin/python-3.5-2/lib/python3.5/site-packages/deeptools/getFragmentAndReadSize.py", line 11, in getFragmentLength_wrapper
    return getFragmentLength_worker(*args)
  File "/home/test/bin/python-3.5-2/lib/python3.5/site-packages/deeptools/getFragmentAndReadSize.py", line 49, in getFragmentLength_worker
    for r in bam.fetch(chrom, start, end)])
  File "/home/test/bin/python-3.5-2/lib/python3.5/site-packages/deeptools/getFragmentAndReadSize.py", line 49, in <listcomp>
    for r in bam.fetch(chrom, start, end)])
**TypeError: infer_query_length() takes no keyword arguments**
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/bin/python-3.5-2/bin/bamCoverage", line 11, in <module>
    main(args)
  File "/home/test/bin/python-3.5-2/lib/python3.5/site-packages/deeptools/bamCoverage.py", line 249, in main
    verbose=args.verbose,
  File "/home/test/bin/python-3.5-2/lib/python3.5/site-packages/deeptools/countReadsPerBin.py", line 176, in __init__
    verbose=verbose)
  File "/home/test/bin/python-3.5-2/lib/python3.5/site-packages/deeptools/getFragmentAndReadSize.py", line 96, in get_read_and_fragment_length
    verbose=verbose)
  File "/home/test/bin/python-3.5-2/lib/python3.5/site-packages/deeptools/mapReduce.py", line 142, in mapReduce
    res = pool.map_async(func, TASKS).get(9999999)
  File "/home/test/bin/python-3.5-2/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
**TypeError: infer_query_length() takes no keyword arguments`**

**Comment by dpryan79** [comment]
Please downgrade pysam to 0.10.0, they randomly changed the API in the most recent version.
