### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by gireeshkbogu** [fidelram/deepTools#549]
Hi, I have successfully installed deepTools. However, when I run any command, I am getting the following error. Any help could be appreciated! thanks

```
$ conda install -c bioconda deeptools
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at //anaconda:
#
deeptools                 2.5.1                    py27_0    bioconda
```

Error:
$ computeMatrix
```
Traceback (most recent call last):
  File "//anaconda/bin/computeMatrix", line 4, in <module>
    from deeptools.computeMatrix import main
  File "//anaconda/lib/python2.7/site-packages/deeptools/computeMatrix.py", line 13, in <module>
    from deeptools import heatmapper
  File "//anaconda/lib/python2.7/site-packages/deeptools/heatmapper.py", line 9, in <module>
    from deeptools import getScorePerBigWigBin
  File "//anaconda/lib/python2.7/site-packages/deeptools/getScorePerBigWigBin.py", line 10, in <module>
    import deeptools.utilities
  File "//anaconda/lib/python2.7/site-packages/deeptools/utilities.py", line 3, in <module>
    import pysam
  File "//anaconda/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: dlopen(//anaconda/lib/python2.7/site-packages/pysam/libchtslib.so, 2): Library not loaded: @rpath/liblzma.5.dylib
  Referenced from: //anaconda/lib/libhts.2.dylib
  Reason: Incompatible library version: libhts.2.dylib requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
```

**Comment by gireeshkbogu** [comment]
It works after running this. thanks anyways. 
`conda update xz`
