### ISSUE TITLE
plotCorrelation 

### ISSUE THREAD

**Issue by mforoozani1** [fidelram/deepTools#565]
Hello,
I used plotcorrelation to visualize the output from multibamsummary.When I used scatterplot (1) , it gave me the output. When I tried to get heatmap(2) it gave me the python error. 
this is the error : 
```
Traceback (most recent call last):
  File "bin/plotCorrelation", line 11, in <module>
    main(args)
  File "/project/maheshid/mforoo1/deeptools/deepTools-2.4.1/lib/python2.7/site-packages/deeptools/plotCorrelation.py", line 209, in main
    plot_numbers=args.plotNumbers)
  File "/project/maheshid/mforoo1/deeptools/deepTools-2.4.1/lib/python2.7/site-packages/deeptools/correlation.py", line 257, in plot_correlation
    link_color_func=lambda k: 'darkred')
  File "/usr/local/packages/Python/2.7.3/gcc-4.4.6/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 2148, in dendrogram
    link_color_func=link_color_func)
  File "/usr/local/packages/Python/2.7.3/gcc-4.4.6/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 2327, in _dendrogram_calculate_info
    nb = Z[ab - n, 3]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
Fri Jul 28 10:05:44 CDT 2017

```

```
1)bin/plotCorrelation -in 3rep_P_C_entiregenome_multibamsummary.npz -p scatterplot -c pearson -o test.png      
2)bin/plotCorrelation -in 3rep_P_C_entiregenome_multibamsummary.npz -p heatmap -c spearman -o spearman_3rep_P_C_entiregenome_multibamsummary.png 
```
I really appreciate any help you can provide.
Maryam

**Comment by vivekbhr** [comment]
@mforoozani1 can you mention the version of deeptools you're using

**Comment by mforoozani1** [comment]
Thanks for response. it is deepTools-2.4.1.


Maryam Foroozani
PhD Candidate
Department of Biological sciences
Louisiana State University
Cell: 3147097378
E-mail: mforoo1@lsu.edu


________________________________

**Comment by dpryan79** [comment]
Can you post the npz file somewhere (or email it to me)? What version of scipy do you have installed?

**Comment by mforoozani1** [comment]
my scipy version : 0.11.0




________________________________

**Comment by mforoozani1** [comment]
deeptool requires 0.17.0 , I am going to update my Scipy.

**Comment by dpryan79** [comment]
@mforoozani1 Did updating scipy fix this issue for you?

**Comment by dpryan79** [comment]
@mforoozani1 If not, feel free to reopen.
