### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by c-guzman** [fidelram/deepTools#579]
Getting a weird little error when trying to run bamCoverage for sequencing data.

```
bamCoverage -b ${bam} -o ${mergeid}.RPKMnorm.bw -of bigwig -bs ${params.bamcoverage_bs} -p ${params.threads} --normalizeUsingRPKM --smoothLength ${params.bamcoverage_smooth} -e ${params.bamcoverage_e} --centerReads 2> ${mergeid}.bamcoverage_report.txt
```

```
Traceback (most recent call last):
  File "/opt/anaconda2/bin/bamCoverage", line 11, in <module>
    main(args)
  File "/opt/anaconda2/lib/python2.7/site-packages/deeptools/bamCoverage.py", line 145, in main
    scale_factor = get_scale_factor(args)
  File "/opt/anaconda2/lib/python2.7/site-packages/deeptools/getScaleFactor.py", line 168, in get_scale_factor
    bam_mapped, bam_mapped_total = get_num_kept_reads(args)
  File "/opt/anaconda2/lib/python2.7/site-packages/deeptools/getScaleFactor.py", line 157, in get_num_kept_reads
    ftk = fraction_kept(args)
  File "/opt/anaconda2/lib/python2.7/site-packages/deeptools/getScaleFactor.py", line 127, in fraction_kept
    verbose=args.verbose)
  File "/opt/anaconda2/lib/python2.7/site-packages/deeptools/mapReduce.py", line 141, in mapReduce
    pool = multiprocessing.Pool(numberOfProcessors)
  File "/opt/anaconda2/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/opt/anaconda2/lib/python2.7/multiprocessing/pool.py", line 138, in __init__
    self._setup_queues()
  File "/opt/anaconda2/lib/python2.7/multiprocessing/pool.py", line 234, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/opt/anaconda2/lib/python2.7/multiprocessing/queues.py", line 354, in __init__
    self._rlock = Lock()
  File "/opt/anaconda2/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/opt/anaconda2/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 2] No such file or directory
```

This is deeptools version 2.5.3 inside a Singularity container installed using anaconda2 mapped using bbmap.

**Comment by dpryan79** [comment]
After a bit of searching around, my only guess is that this is some sort of
issue where the python multiprocessing module has problems accessing
/dev/shm in singularity. That's pretty obscure and not something controlled
by deepTools.

--
Devon Ryan, Ph.D.
Email: dpryan@dpryan.com
Data Manager/Bioinformatician
Max Planck Institute of Immunobiology and Epigenetics
Stübeweg 51
79108 Freiburg
Germany
<devon.ryan@dzne.de>

**Comment by c-guzman** [comment]
Great, let me get in contact with the Singularity devs and see if I can solve this so someone else can benefit in case they run into this problem.

**Comment by dpryan79** [comment]
Sounds good! If there's something they think we should change on our end then let me know. Perhaps there's something with the bioconda recipe that should be changed (I can do that if they have a clue what should be changed).
