### ISSUE TITLE
computeMatrix reference-point should ignore --unscaledXPrime

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#593]
Someone just accidentally did `computeMatrix reference-point` and noticed that you can specify `--unscaled5Prime` (or 3 prime) and that you then get a cryptic error:

    Traceback (most recent call last):
      File "/package/python-3.6.1/lib/python3.6/multiprocessing/pool.py", line 119, in worker
        result = (True, func(*args, **kwds))
      File "/package/python-3.6.1/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
        return list(map(*args))
      File "/package/deeptools-2.5.3/lib/python3.6/site-packages/deeptools/heatmapper.py", line 173, in compute_sub_matrix_wrapper
        return heatmapper.compute_sub_matrix_worker(*args)
      File "/package/deeptools-2.5.3/lib/python3.6/site-packages/deeptools/heatmapper.py", line 566, in compute_sub_matrix_worker
        sub_matrix[j, :] = coverage
    ValueError: could not broadcast input array from shape (200) into shape (280)

I imagine this some side-effect of those values being non-zero. A simple fix would be to simply set them to 0 in `reference-point`.

**Comment by dpryan79** [comment]
This is now fixed in `develop`.
