### ISSUE TITLE
bamCoverage should support "empty" bigWigs

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#598]
C.f. [here](https://bioinformatics.stackexchange.com/questions/2516/dealing-with-absence-of-coverage).

In short, in at least some versions of deepTools bamCoverage would throw an error if not entries were actually written to the temporary bedGraph files. I don't know if this is still the case, but if it is then it should be fixed.

**Comment by blaiseli** [comment]
I tried commit bbe3cff11c087b7b9dadbbf20a14c3e606ee37dd, and there is still an error, but different:

```
[bwClose] There was an error while finishing writing a bigWig file! The output is likely truncated.
```

Here is the command I used:
```
bamCoverage -b /tmp/test_sorted.bam --skipNAs --filterRNAstrand reverse -of=bigwig -bs 10 -p=1 -o /tmp/test.bw
```

And here is the sam file corresponding to the sorted and indexed bam file used above:

```
$ cat /tmp/test.sam 
@HD	VN:1.0	SO:coordinate
@SQ	SN:I	LN:15072434
@SQ	SN:II	LN:15279421
@SQ	SN:III	LN:13783801
@SQ	SN:IV	LN:17493829
@SQ	SN:MtDNA	LN:13794
@SQ	SN:V	LN:20924180
@SQ	SN:X	LN:17718942
@PG	ID:bowtie2	PN:bowtie2	VN:2.3.2	CL:"/home/bli/src/bowtie2-2.3.2/bowtie2-align-s --wrapper basic-0 --seed 123 -t -L 6 -i S,1,0.8 -N 0 --mm -x /pasteur/entites/Mhe/Genomes/C_elegans/Caenorhabditis_elegans/Ensembl/WBcel235/Sequence/Bowtie2Index/genome --passthrough -U results_csr1_ADH_IP/bowtie2/mapped_C_elegans/reads/WT_38hph_IP_1_18-26_on_C_elegans/simrep_siuRNA.fastq.gz"
MN00481:9:000H23JFH:1:11103:8754:2964	16	I	6022019	42	20M	*	0	0	TTTTAATTCTCGTTTTCTAC	FFFFFFFFFFFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:20	YT:Z:UU
MN00481:9:000H23JFH:1:21105:11648:2155	16	I	6022496	42	22M	*	0	0	GGAACATTTCAAGAATAACTAC	FFFFFFFFFFFFFFFFFFFFFA	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:22	YT:Z:UU
MN00481:9:000H23JFH:1:13106:18657:14684	16	II	4050599	42	22M	*	0	0	TTTCGCGCGCTCTCTCTTTCTC	FFFFFFFFFF/FFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:22	YT:Z:UU
MN00481:9:000H23JFH:1:11106:21539:3394	16	II	14066688	42	22M	*	0	0	TGTCCTATTTATTTATTTTATC	FFFFFFFFFFFFFFFFFF/FFA	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:22	YT:Z:UU
MN00481:9:000H23JFH:1:21107:17476:19419	16	II	14066723	42	22M	*	0	0	TTTGTATTTTTCACCGCATTTC	FFFFFFFFFFFFFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:22	YT:Z:UU
MN00481:9:000H23JFH:1:23104:13146:3242	16	II	15229619	42	22M	*	0	0	CTCTCTCCCGCTCTCCCACCTC	FF=FFFFFAFFFFFFFFFFFFA	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:22	YT:Z:UU
MN00481:9:000H23JFH:1:11104:23298:5836	16	II	15264897	1	19M	*	0	0	TCCTCTCTCTCTCTCTCTC	FFFFFFFFFFFFFFFFFFF	AS:i:0	XS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:19	YT:Z:UU
MN00481:9:000H23JFH:1:12109:10633:1101	16	III	862079	42	22M	*	0	0	TCCGTCGTTTCTTTCTCATTTC	FFFFFFFFFFFFFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:22	YT:Z:UU
MN00481:9:000H23JFH:1:23105:19627:16877	16	III	862139	42	22M	*	0	0	GTTCAACCGTCGTGGTTTTCAC	A/AAFAF/FFFFF/F6FFF/AF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:22	YT:Z:UU
MN00481:9:000H23JFH:1:12104:23867:2382	16	III	2960741	1	22M	*	0	0	TTCAGAAATTTATCGATTTTTC	FFFFFFFFFFFFFFFFFFFFFF	AS:i:0	XS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:22	YT:Z:UU
MN00481:9:000H23JFH:1:23109:13429:3967	16	III	12744640	42	22M	*	0	0	TCTTTTATCTGTGTCGATTTAC	FFFFFFFFFFFFFAFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:22	YT:Z:UU
MN00481:9:000H23JFH:1:23105:21462:6514	16	III	13546365	40	22M	*	0	0	GAGATTGAGATGGGCAGAACAC	FF=F/FAF=FA/FF/F//FFFA	AS:i:-3	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:4A17	YT:Z:UU
MN00481:9:000H23JFH:1:12104:19733:8737	16	IV	7585854	1	20M	*	0	0	TCTGCTGCTGCTGCTGCTGC	/FFFFFFFFFFFFFFFFF=A	AS:i:0	XS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:20	YT:Z:UU
MN00481:9:000H23JFH:1:12101:17438:3561	16	V	3704117	23	20M	*	0	0	TCTCCCACTGCTGCTGCTGC	FFFFFFFAFFFFFFFFFFFF	AS:i:-5	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:6T13	YT:Z:UU
MN00481:9:000H23JFH:1:13104:18246:17719	16	V	3704117	23	20M	*	0	0	TCTCCCACTGCTGCTGCTGC	FFFF/FFFFFFFFFF/FF=A	AS:i:-5	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:6T13	YT:Z:UU
MN00481:9:000H23JFH:1:13103:24485:8926	16	X	12852463	23	19M	*	0	0	TTTCCACCTCCCCCTCATC	FFFFFFFFFFFFFFFFFFF	AS:i:-5	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:11T7	YT:Z:UU
```

**Comment by dpryan79** [comment]
@blaiseli Thanks I'll have this fixed for version 2.6, which is due out in about 2 weeks.

**Comment by dpryan79** [comment]
It turns out that this is an issue with pyBigWig.

**Comment by dpryan79** [comment]
Even UCSC can't make an empty bigWig file, it ends up just making a 384 byte file with almost all 0s. I'll just alter pyBigWig/libBigWig to make a file that they can open and recognize as being empty.

**Comment by dpryan79** [comment]
@blaiseli Please test this with the master branch of pyBigWig from github. I think I have the issue resolved there and it's behaving in a way that shouldn't require any deepTools changes.

**Comment by dpryan79** [comment]
With pyBigWig 0.3.5 this should now work.

**Comment by blaiseli** [comment]
I confirm there is no more error with pyBigWig 0.3.5 and deeptools https://github.com/fidelram/deepTools/commit/bbe3cff11c087b7b9dadbbf20a14c3e606ee37dd

Thanks

**Comment by dpryan79** [comment]
Great, thanks!

**Comment by mohammedkhalfan** [comment]
Hello, I believe I am having the same issue. I am attempting to create a bigwig using bamCoverage from a bam that has no reads (one of the samples being analyzed in the pipeline has this condition) and I get this failure:
```
bamCoverage -p max --bam CV-40_haplotypecaller_bamout.bam --binSize 1 --ignoreDuplicate
s --minMappingQuality 20 -o CV-40-hc_bamout_coverage.bam.bw
WARNING! 'CV-40_haplotypecaller_bamout.bam' does not have any mapped reads. Please check that the file is properly indexed and that it
contains mapped reads.
WARNING! 'CV-40_haplotypecaller_bamout.bam' does not have any mapped reads. Please check that the file is properly indexed and that it contains mapped reads.
Traceback (most recent call last):
  File "/share/apps/deeptools/3.4.3/bin/bamCoverage", line 12, in <module>
    main(args)
  File "/share/apps/deeptools/3.4.3/lib/python3.8/site-packages/deeptools/bamCoverage.py", line 256, in main
    wr.run(writeBedGraph.scaleCoverage, func_args, args.outFileName,
  File "/share/apps/deeptools/3.4.3/lib/python3.8/site-packages/deeptools/writeBedGraph.py", line 131, in run
    genome_chunk_length = getGenomeChunkLength(bam_handles, self.binLength, self.mappedList)
  File "/share/apps/deeptools/3.4.3/lib/python3.8/site-packages/deeptools/writeBedGraph.py", line 337, in getGenomeChunkLength
    genomeChunkLength = int(min(5e6, int(2e6 / (max_reads_per_bp * len(bamHandles)))))
ZeroDivisionError: float division by zero
```

**Comment by LeilyR** [comment]
I am afraid your issue is different. You got a meaningful warning that says you had no mapped read (if your indexing was right). I assume the reported issue was for a case with a few mapped reads scattered over the genome.

**Comment by dpryan79** [comment]
I think in the original report all of the alignments were getting filtered out or maybe this is from when pyBigWig couldn't create files without entries.

I'm a bit torn on this. On the one hand, it'd be nice if workflows could just run through, getting empty bigWig files. On the other hand that will likely cause errors later on and as an analyst I'd like to know if some of my samples completely failed. So maybe a happy compromise is an `--allowEmptyFiles` option?

**Comment by mohammedkhalfan** [comment]
I have the same dilemma. Your solution would allow the option when desired. Thank you.

**Comment by ddepierre** [comment]
Hi, 
I was wondering if the --allowEmptyFiles option had been added in a recent deeptools version ? It could probably solve my issue : I've got some empty bam files (over dozen) that shut down my snakemake pipeline using deeptools because of these errors. 
I'm gonna try an alternative with something like "if empty bam then touch a bigwig file" but I would appreciate this option!

Best,
David

**Comment by dpryan79** [comment]
@ddepierre I think your work-around is the only option at this point.
