### ISSUE TITLE
computeMatrix & plotHeatmap error with >1 bed files

### ISSUE THREAD

**Issue by venuthatikonda** [fidelram/deepTools#607]
Hi,

I'm trying to use `computeMatrix` and `plotHeatmap` functions with 2 bed files as described in the manual [here](http://deeptools.readthedocs.io/en/latest/content/tools/plotHeatmap.html#usage-examples).

Here is the message and error I've got using `computeMatrix` and `plotHeatmap` respectively

computeMatrix
```
~/myTools/deepTools/bin/computeMatrix reference-point --referencePoint center -b 4000 -a 4000 -R /b06x-isilon/b06x-a/ATRT_drosophila/results/orthologsTested/significant_tss_allTranscripts.bed /b06x-isilon/b06x-a/ATRT_drosophila/results/orthologsTested/notSignficant_tss_allTranscripts.bed -S /b06x-isilon/b06x-a/ATRT_drosophila/results/bigWig/H3K27ac/MYC*.bw --skipZeros -o test2beds.gz
```
message
```
Skipping chr1:933552-938552, due to being absent in the computeMatrix output.
Skipping chr1:33813499-33818499, due to being absent in the computeMatrix output.
...
```

plotHeatmap
```
~/myTools/deepTools/bin/plotHeatmap -m test2beds.gz --samplesLabel MYC_ATRT_01 MYC_ATRT_02 MYC_ATRT_03 MYC_ATRT_04 --plotTitle "H3K27ac signal at promoters" --yAxisLabel promoters -out MYC_Promoters_H3K27ac_2beds.png --colorMap RdBu -min -3 -max 3
```
error
```
Traceback (most recent call last):
  File "/b062-h/thatikon/myTools/deepTools/bin/plotProfile", line 11, in <module>
    main(args)
  File "/usr/lib64/python2.7/site-packages/deeptools/plotProfile.py", line 500, in main
    hm.read_matrix_file(matrix_file)
  File "/usr/lib64/python2.7/site-packages/deeptools/heatmapper.py", line 775, in read_matrix_file
    sample_labels=self.parameters['sample_labels'])
  File "/usr/lib64/python2.7/site-packages/deeptools/heatmapper.py", line 1022, in __init__
    "row max do not match matrix shape"
AssertionError: row max do not match matrix shape
```

Help would be greatly appreciated. I'm using version - 2.4.2-4-999ec5d.

**Comment by dpryan79** [comment]
Please upgrade to the most recent version (actually, anything since 2.5.0) and rerun `computeMatrix`. There was a bug in a number of the older version that caused this behavior.
