### ISSUE TITLE
bamCompare No space left on device issue

### ISSUE THREAD

**Issue by avilella** [fidelram/deepTools#87]
I also tried bamCompare and got this error below. Any ideas?

```
bamCompare -b1 /data/test1.bam -b2 /data/test2.bam --binSize 250 --fragmentLength 200 --missingDataAsZero no --ratio log2 --scaleFactorsMethod SES -o log2ratio.bw
^[xThe scaling factors are:
[ 0.56656238  1.        ]
Traceback (most recent call last):
  File "/opt/python/2.7.3/bin/bamCompare", line 388, in <module>
    main(args)
  File "/opt/python/2.7.3/bin/bamCompare", line 384, in main
    samFlag=args.samFlag)
  File "/opt/python/2.7.3/lib/python2.7/site-packages/deeptools/writeBedGraph.py", line 287, in writeBedGraph
    numberOfProcessors=numberOfProcessors)
  File "/opt/python/2.7.3/lib/python2.7/site-packages/deeptools/mapReduce.py", line 116, in mapReduce
    res = pool.map_async(func, TASKS).get(9999999)
  File "/opt/python/2.7.3/lib/python2.7/multiprocessing/pool.py", line 528, in get
    raise self._value
IOError: [Errno 28] No space left on device

**Comment by avilella** [comment]
If the issue is due to data being copied to `/tmp`, is there a `--tmpdir` option to set it to a different place?

**Comment by fidelram** [comment]
The way to set a temp dir is through the configuration file. Check for a file called deeptools.cfg in your installation path. This is how the file looks like https://github.com/fidelram/deepTools/blob/master/deeptools/config/deeptools.cfg

To get the context of the error message you can turn off multiprocessing (add -p 1).

**Comment by fidelram** [comment]
Did the solution worked for you?
