### ISSUE TITLE
{compute,correct}GCBias errors

### ISSUE THREAD

**Issue by radaniba** [fidelram/deepTools#96]
Hello 

I am using the latest version of deepTools and I am running through this error while running the {compute, correct}GCBias pair : 

```
Traceback (most recent call last):
  File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/bin/computeGCBias", line 10, in <module>
    from scipy.stats import poisson
  File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/stats/__init__.py", line 321, in <module>
    from .stats import *
  File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/stats/stats.py", line 180, in <module>
    import scipy.special as special
  File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/special/__init__.py", line 603, in <module>
    from .basic import *
  File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/special/basic.py", line 18, in <module>
    from . import orthogonal
  File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/special/orthogonal.py", line 101, in <module>
    from scipy import linalg
  File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/linalg/__init__.py", line 188, in <module>
    from ._decomp_update import *
  File "scipy/linalg/_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update (scipy/linalg/_decomp_update.c:35875)
ImportError: /genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/linalg/cython_lapack.so: undefined symbol: zlacn2_
```

Any idea on what can cause this ?

ps : am using scipy 0.16.0

**Comment by radaniba** [comment]
Ok I downgraded to Scipy 0.12 and it worked

Any dependencies specs somewhere in the doc ?

**Comment by fidelram** [comment]
Hi,

This is an error from scipy. See this answer:
http://stackoverflow.com/questions/32011231/undefined-symbol-in-scipys-lapack-library

-fidel

On Thu, Aug 20, 2015 at 11:04 PM, Radhouane Aniba <notifications@github.com>
wrote:

> Hello
>
> I am using the latest version of deepTools and I am running through this
> error while running the {compute, correct}GCBias pair :
>
> Traceback (most recent call last):
>   File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/bin/computeGCBias", line 10, in <module>
>     from scipy.stats import poisson
>   File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/stats/__init__.py", line 321, in <module>
>     from .stats import *
>   File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/stats/stats.py", line 180, in <module>
>     import scipy.special as special
>   File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/special/__init__.py", line 603, in <module>
>     from .basic import *
>   File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/special/basic.py", line 18, in <module>
>     from . import orthogonal
>   File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/special/orthogonal.py", line 101, in <module>
>     from scipy import linalg
>   File "/genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/linalg/__init__.py", line 188, in <module>
>     from ._decomp_update import *
>   File "scipy/linalg/_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update (scipy/linalg/_decomp_update.c:35875)
> ImportError: /genesis/extscratch/shahlab/pipelines/virtual_environments/chip-seq/lib/python2.7/site-packages/scipy/linalg/cython_lapack.so: undefined symbol: zlacn2_
>
> Any idea on what can cause this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/96>.
>



-- 

Fidel Ramirez

**Comment by fidelram** [comment]
Hi,

The error was from scipy, not from deepTools. Something was wrong with your installation.   

I have tested deepTools with the latest scipy version 0.15. In the setup.py says that deepTools requires scipy >= 0.10

Fidel Ramírez

**Comment by radaniba** [comment]
Hi @fidelram !
Thanks yes I saw this and fixed my isue by downgrading scipy and it worked just fine. Thank you
